### ISSUE TITLE
Slack Dropping IRC Support -- Opinions?

### ISSUE THREAD

**Issue by StrangeWill** [devanooga/devanooga-meta#39]
Got this from DC423 this morning:

https://it.slashdot.org/story/18/03/08/2049255/slack-is-shutting-down-its-irc-gateway

I know some of our users use the IRC gateway, and it's a huge deal for them.

@wvaladez pointed out that wee-slack is an option: https://github.com/wee-slack/wee-slack is this good enough?

Do we need to figure out another solution? Hmm.

**Comment by wvaladez** [comment]
I will be testing wee-slack in the near future and report my opinion. I'm not sure there are other good options other than slack-term which seems inferior to weechat's wee-slack plugin. 

I think the other option is to move to an ircd, but the number of users who prefer the extra bells and whistles of slack is probably significantly larger than the users who utilize the irc gateway.

**Comment by wvaladez** [comment]
Weechat + wee-slack seems great. I've managed to configure it nearly identically to irssi. and keep all my chats under one client. It has a lot of other interesting features that irssi and other console clients don't as well. I think it's more than suitable for folks who are used to the irc gateway. 

My one complaint is that wee-slack is a little rough around the edges. The functionality is better than the irc gateway for sure, but some of the weechat formatting options don't seem to apply very well to the slack buffers. I imagine that will improve in time.

**Comment by StrangeWill** [comment]
We set up our own bridge -- currently only bridges `#random` but works well.
