### ISSUE TITLE
501c3 Status is incorrect.

### ISSUE THREAD

**Issue by Digi59404** [devanooga/devanooga-meta#66]
This file says 501c3 status is in progress. It has been completed. The readme needs to be changed to reflect this. https://github.com/devanooga/devanooga-meta/blob/master/legal/readme.md

**Comment by StrangeWill** [comment]
I love how it's next to the `501c3.md` document detailing all of that.

Yeah I really need to make an update pass on this.

**Comment by StrangeWill** [comment]
Fixed in daaa9a4921ef1af436af7b5af88f290241b814a9
